POST http://localhost:8081/users/registration
Content-Type: application/json

{
  "username": "testusername",
  "nickname": "testnickname",
  "email": "testname@mockemail.com",
  "password": "password",
  "birthday": "2000-12-01",
  "contactNumber": "010-1234-5678"
}

###
POST http://localhost:8081/users/authentication
Content-Type: application/json

{
  "email": "testname@mockemail.com",
  "authenticationCode": "88-6cbd-47dd-8077-4f0f37bbfd27"
}

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "testusername",
  "password": "password"
}
