POST http://localhost:8081/users/registration
Content-Type: application/json

{
  "username": "testname",
  "nickname": "testname",
  "email": "ujaekim012@gmail.com",
  "password": "password",
  "birthday": "2000-12-01",
  "contactNumber": "010-1234-5678"
}

###
POST http://localhost:8081/users/authentication
Content-Type: application/json

{
  "email": "ujaekim012@gmail.com",
  "authenticationCode": "fb-b44e-4e7d-8474-5c09ffbb846d"
}
