POST http://localhost:8081/users/registration
Content-Type: application/json

{
  "username": "testusername",
  "nickname": "testnickname",
  "email": "",
  "password": "password",
  "birthday": "2000-12-01",
  "contactNumber": "010-1234-5678"
}

###
POST http://localhost:8081/users/authentication
Content-Type: application/json

{
  "email": "",
  "authenticationCode": ""
}

###
POST http://localhost:8081/login
Content-Type: application/json

{
  "username": "testusername",
  "password": "password"
}
