server:
  port: 8000

spring:
  application:
    name: ecommerce-api-gateway
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
          args:
            baseMessage: Spring Cloud Gateway Logging Filter
            preLogger: true
            postLogger: true
      routes:
        - id: api-server-router
          uri: lb://ECOMMERCE-USER
          predicates:
            - Path=/ecommerce-user/**
          filters:
            - name: JwtFilter
              args:
                baseMessage: Spring Cloud Gateway Jwt Filter
                excludePaths:
                  - /ecommerce-user/users/authentication
                  - /ecommerce-user/users/registration
                  - /ecommerce-user/users/login
            - RewritePath=/ecommerce-user/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
