version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - '3306:3306'
  redis:
    container_name: redis
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'


