server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/the-developer-lab/the-msa-lab-private-config
management:
  server:
    port: 18888
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        include: info, health
    web:
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
